### ISSUE TITLE
Update spec for Tilt events to include unique addressing and improved property names

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-tilt#2]
## Context

This issue is a combination of three changes that all would involve changing field names as published to the history database.
To limit disruption for end users, changes are grouped in this issue.

This issue is a proposal for implementation, and serves as Request For Comments (RFC).

## Desired changes

**Repeated colors**
Tilt devices are identified by iBeacon UUID and device MAC address. The UUID is unique per color, the MAC address is unique per device. Currently, data is published by color only. This means that if there are multiple Tilts with the same color present, their values will be mixed.

To support unique devices with a shared color, they must have a unique name in published data. A MAC address or randomly generated name will not be user-recognizable, and some mechanism must be present to set user-defined names for individual devices.

The majority of users will not have multiple Tilts of the same color. The naming scheme should reflect this.

**Calibrated values by default**
The current spec always publishes raw values as `Temperature[degC]`, `Temperature[degF]`, `Specific gravity`, `Plato[degP`.
If calibration data is present, the `Calibrated temperature[degC]`, `Calibrated temperature[degF]`, `Calibrated specific gravity`, and `Calibrated plato[degP]` fields are added.

Users must now explicitly opt-in to use calibrated values. The presence of calibration data suggests user intent, so an opt-out system is more appropriate.
This would mean that the default fields (`Temperature`, `Specific gravity`, `Plato`) show the calibrated values if available, and uncalibrated otherwise.
If calibrated values are available, the uncalibrated values remain relevant, and should be published alongside.

**Field names**
Published fields are currently sentence cased, with the first word capitalized, and spaces separating words.
If breaking changes are inevitable with the introduction of device-unique field names, then this is the right moment to do some cleanup, and convert field names to the more traditional camel case (every word except the first capitalized, no spaces) or pascal case (all words including the first capitalized, no spaces).

By default, the rest of the Brewblox software uses US spelling. To bring the Tilt service in line, the "colour" field in the state event will be renamed to "color".

## Implementation

**Device name**
The concept of a "device name" is introduced here. When first detected, devices are assigned a default name. The first device of a given color will be named after the color. Subsequent devices will have a postfixed incremental number.
For example, if three red Tilts are detected, their names will be:
- Red
- Red-2
- Red-3

Because assigned names are not deterministic, they must be stored on disk. For this purpose, a new config file is introduced: `/share/devices.yml`. This file is read on startup, and written to whenever a new device name is assigned.
Names are stored under the top-level `names` key, where the value is the desired name, and the key is an uppercase MAC address without `:` separators.
Users may add or edit device names stored here, but must be aware that the service may overwrite the file while active, and must be reloaded before changes are used.

User-defined device names must:
- Consist of alphanumeric characters, space, and `_-()|`.
- Contain at least 1, and at most 100 characters.

Any names that do not meet these requirements will be sanitized on startup.

```yml
names:
  AA7F97FC141E: Orange
  DD7F97FC141E: Purple
```

The existing `/share/SGCal.csv` and `/share/tempCal.csv` can use either MAC addresses or device names as identifier.
Device names that contain spaces must be quoted. Here, names are case-insensitive to preserve backwards compatibility.

While assigned device names are guaranteed to be unique, user-defined device names are not required to be unique.
If multiple devices with the same name are active simultaneously, their data will be mixed in history events. State events are identified by mac, and will remain separate.

**Editing device names**
The Tilt service cannot access the Brewblox datastore as it is not connected to the bridge network, and may not even be running on the same host. It is guaranteed to be connected to the eventbus. We can publish desired device names here.
To update one or more device names, a message should be published with the topic `brewcast/tilt/${SERVICE}/names`, and as payload a JSON object containing changed values. Valid values in this object will be merged with other known values, and written to `/share/devices.yml`. It is not possible to remove device names this way.

Example:
Topic=brewcast/tilt/tilt/names
Payload=
```json
{
  "AA7F97FC141E": "Fermentation 1 Tilt",
  "DD7F97FC141E": "Purple"
}
```

**Field names**
Tilt values will include the following fields:
- `temperature[degF]`: Measured temperature in Fahrenheit. Calibrated if calibration data is available, uncalibrated otherwise.
- `temperature[degC]`: Measured temperature in Celsius. Calibrated if calibration data is available, uncalibrated otherwise.
- `specificGravity`: Measured SG. Calibrated if calibration data is available, uncalibrated otherwise.
- `plato[degP]`: Measured SG in Plato. Calibrated if calibration data is available, uncalibrated otherwise.
- `rssi[dBm]`: Received signal strength of the Tilt beacon.

The below fields are only present if calibration data is available.
- `uncalibratedTemperature[degF]`: Measured temperature in Fahrenheit, as received from the Tilt.
- `uncalibratedTemperature[degC]`: Measured temperature in Celsius, as received from the Tilt.
- `uncalibratedSpecificGravity`: Measured SG, as received from the Tilt.
- `uncalibratedPlato[degP]`: Measured SG in Plato, as received from the Tilt.

**History events**
```json
{
  "key": "tilt",
  "data": {
    "Purple": {
      "temperature[degF]": 68,
      "temperature[degC]": 20,
      "specificGravity": 1.052,
      "plato[degP]": 15,
      "rssi[dBm]": -80
    },
    "Fermentation 1 Tilt": {
      "temperature[degF]": 68,
      "temperature[degC]": 20,
      "specificGravity": 1.052,
      "plato[degP]": 15,
      "rssi[dBm]": -80,
      "uncalibratedTemperature[degF]": 68,
      "uncalibratedTemperature[degC]": 20,
      "uncalibratedSpecificGravity": 1.052,
      "uncalibratedPlato[degP]": 15
    }
  }
}
```
Notes:
- `key` is the service name.
- keys in `data` are device names, either default or user-defined.

**State events**
Topic=brewcast/state/tilt/Orange/AA7F97FC141E
Payload=
```json
{
  "key": "tilt",
  "type": "Tilt.state",
  "timestamp": 1636813164306,
  "color": "Orange",
  "mac": "AA7F97FC141E",
  "name": "Fermentation 1 Tilt",
  "data": {
      "temperature[degF]": 68,
      "temperature[degC]": 20,
      "specificGravity": 1.052,
      "plato[degP]": 15,
      "rssi[dBm]": -80,
      "uncalibratedTemperature[degF]": 68,
      "uncalibratedTemperature[degC]": 20,
      "uncalibratedSpecificGravity": 1.052,
      "uncalibratedPlato[degP]": 15
  }
}
```
Notes:
- The topic is formatted as `${SERVICE}/${COLOR}/${MAC}` regardless of device name.
- `key` is the service name.
- `type` is a constant.
- `timestamp` is a UTC date in milliseconds.
- `color` is the Tilt color, as determined by its UUID.
- `mac` is the MAC address, formatted as specified above (uppercase, without separators).
- `name` is the device name: user-defined or default.
- `data` is equal to the data published in history events.

**Comment by astephon88** [comment]
I do agree that the flexibility of identifying devices by unique identifier vs color is useful; however, I still think it's useful to be able to address the devices by color as the manufacturer originally intended (especially for novice users). While I see where it would add some complexity, the tiltpi application solved this by giving a configuration option that allows the user to choose if they want to address the devices by mac or color. I think this is a good compromise between backwards compatibility/user friendliness and flexibility

**Comment by steersbob** [comment]
Going through the proposal, this would mostly impact how the default device name is generated.

An alternative is to read + write configuration files, and increment generated device names.
For every discovered Tilt, an entry in the name list is added, leading to eg.
- Purple
- Purple-2
- Purple-3

If you have a single tilt, everything works out of the box. If you have more than one, you probably want to rename them, and override the generated name.

To avoid race conditions in /share/config.yml, this would require a second config file (/share/discovered.yml ?) where generated names are stored.
Every time newly discovered Tilts are published, both files are opened. Names in config.yml override discovered.yml, and if no name is found, a new one is added to discovered.yml.

Pro: a somewhat smoother implementation for users.
Con: more config files, and we really need to add explicit instructions for setting names.

**Comment by steersbob** [comment]
Updated the initial issue to use more user-friendly assigned device names, and to add a mechanism for editing device names in the UI.

**Comment by astephon88** [comment]
Looks like good compromises all around to me

**Comment by steersbob** [comment]
Updated issue to reflect that user-defined device names do not have to be unique, and that keys in calibration data are case-insensitive.
